### ISSUE TITLE
Android-小米手机Toast自带应用名问题

### ISSUE THREAD

**Issue by lodgkk** [yangchong211/YCDialog#2]
if (toast == null) {
            toast = Toast.makeText(mApp, content, Toast.LENGTH_SHORT);
        } else {
            toast.setText(content);
        }
改成
if (toast == null) {
            toast = Toast.makeText(mApp, "", Toast.LENGTH_SHORT);
            toast.setText(content);
        } else {
            toast.setText(content);
        }

**Comment by yangchong211** [comment]
已经修改，谢谢反馈
